### ISSUE TITLE
Custom server stats

### ISSUE THREAD

**Issue by Johnorable** [Harry-Lees/Aston-Unofficial-Bot#13]
I wouldn't mind getting rid of that stats bot :)

**Comment by Harry-Lees** [comment]
Sure, you can add some bullet points maybe of some of the things you'd like to add. Currently we have:

* Stats of Verified Members with the `!profile` command.
* A massive dump of server stats with the `!stats` command.

**Comment by Harry-Lees** [comment]
We also now have:

* `!message_stats` which shows stats about the number of messages sent in each channel.
* `!member_log` which shows information about the number of people in the server.
* `!join_log` which shows information about people joining the server.

**Comment by Jan-art** [comment]
> We also now have:
> 
> * `!message_stats` which shows stats about the number of messages sent in each channel.
> * `!member_log` which shows information about the number of people in the server.
> * `!join_log` which shows information about people joining the server.

VERY NICEEEEEE

**Comment by Harry-Lees** [comment]
I think I will close this issue now and add more server stats on the fly if that is required. Someone can re-open this issue if you have several more ideas.
